{% set version = "6.0.1" %}

package:
  name: cdat-lite
  version: {{ version }}

source:
  fn: cdat_lite-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/cdat-lite/cdat-lite-{{ version }}.tar.gz
  sha256: 092ae4ff1fb03dee00096e8dd595b769b422759ce972d96525950adf8e1c9374

build:
  number: 2
  skip: True  # [win or py3k]
  script:
    - export NETCDF_HOME=$PREFIX
    - export HDF5_HOME=$PREFIX
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - libnetcdf 4.4.*
  run:
    - python
    - setuptools
    - numpy x.x
    - libnetcdf 4.4.*

test:
  imports:
    - cdat_lite
    - cdtime
    - cdms2
  commands:
    - cddump -h
    - cdscan -h
    - conda inspect linkages -p $PREFIX cdat-lite  # [not win]
    - conda inspect objects -p $PREFIX cdat-lite  # [osx]

about:
  home: https://github.com/cedadev/cdat_lite
  license: CCLRC
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A Python package for managing and analysing climate science data.'

extra:
  recipe-maintainers:
    - ocefpaf
