travis:
  secure:
    BINSTAR_TOKEN: HI1uiJR1BYGAQMi63O3fqOKxAN2M89RWRKukdpd9y04im+iqwjbI8y22DvHci4L1pQTBSFgX0XHei2ljwnMwxanqhLxkA7dn2bw8aWIp3LbmIC4okjXqC6wgDxryv2zsQRHvi8R3J9fbN2RZroGp8vBYJjPDBcMT7g8jGVCZaHD9+artCvZmVxi2nl7/FF+yHpTrUHf9jjvzsoXDz2rEhv9T4ijEhfq2wurMxwtg4K0KcpZEreEXOptd/WOuRwzDWl76+T66BbOErXcXL6JTPHohRfIMCwRKYxWPYDPtYHHK6IGcHRiaGHt0mfw6ELvMiQY53v7VrKe6RWbbTGlpZ9mYh8GFgjJQdOeZviqp2lfjWd5dt/rGUJQBiJsEI3KckP8t5dcvdu5G7p8pYLUpOJEE1uN9aty9pyw4C1g2vHsZkYaQpaMni3RIKrZiQonFGgsTwaPKetF70HHCa3ZnxhQxe4oAyTPHeCJdVCM1xBkZ6NCAnnKviooPerteI7eTCxsT1PNBwg6TbAm+9D7sBrrkXt7SvbVjfk4aY778W4kOJx4YWtS1B0ugenmNib3KvZ8ij/vc6IxcljtuNBjva6xpgGhujWlP2NSK07ZS3tHpaylPMEzfnWF2RiIWBTBkfwrwk2ES/capMNLOc5O14DMR7ag2wOrXhW4fInhWxuA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
