travis:
  secure:
    BINSTAR_TOKEN: ubkrWT0XhX46F/bvwVmnSDo74Cnam5uunbt6yyUTHJg9zUag7GS/cAdojzJwdlbARqIN4Y2RAgROvoYmHfmxlLk9/6cRVzoCEoGDeh/trMaUTEMukfARKZUwxJvHo334sesrw+MS0sYFKqh5cbnQZwAZPCcO4f24XQwUd+a46xtOSOBz8vOtQdXiohrqEWwne4wJJ0H+WCANSz2m69yCbFzu76nJPD3MBLcb6oup+EUt+6NQLD4kWYg2NDS/DqmC46+VfGQ3FQK7gDNCLFjXs4fXCs34ibaznb6hE4TmI89zfEcyK3RdOQNrjzccrvmw0thdO9cNCgeWigOsCyhhSY1CrjiWeqNL7X1x741L0n7VUti0ffWipFxVPMXCPJI+2Liqmj2WkRo0AiULodLb4Tv0H9uAicZV+mRd5EBYyxz+RLwbOiWmi7WkLroR6mVUG1/T4EUHP5Bvliov1BYi1ld5zRFXPTVgJoXxNdBKrIIFJgmTwud7iiaxAbwwGQloLSqp7P/VWo3n06l7hrL10Q2NeWMwZjxfe/rdzSJ/lcvh8m92p16zvstSxhqpEkuMYSMVl43lFyY0+osORifhzFINMAiaZNyewaD3bcgreNIKGsmX3gxfM39nfi0JARMPfJXP1k5TuvxDMl3lvaMqWYIAAYSVf7P/owDQiUDTDrs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
